<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=1000" />
    <title>Bdrops Pictures</title>
    <link media="all" rel="stylesheet" type="text/css" href="<?php echo App::getBaseUrl() ?>/skin/css/all.css" />
    <link href='http://fonts.googleapis.com/css?family=Cabin:400,600,700' rel='stylesheet' type='text/css' />
    <script type="text/javascript" src="<?php echo App::getBaseUrl() ?>/skin/js/jquery-1.8.2.min.js"></script>
    <script type="text/javascript" src="<?php echo App::getBaseUrl() ?>/skin/js/jquery.main.js" ></script>
    <!--[if lt IE 8]><link rel="stylesheet" type="text/css" href="<?php echo App::getBaseUrl() ?>/skin/css/ie.css" /><![endif]-->
</head>
<body>
<div id="wrapper">
    <div class="w1">
        <div class="w2">
            <div id="header">
                <div class="holder">
                    <strong class="logo"><a href="#">Bdrops Pictures</a></strong>
                    <ul class="tools">
                        <li><a class="home" href="#">home</a></li>
                        <li><a class="zoom" href="#">zoom</a></li>
                    </ul>
                </div>
            </div>
            <div id="main">
                <div id="sidebar" class="open-close-wrapper">
                    <div class="holder">
                        <div id="open-close">
                            <div class="block">
                                <h2 class="avatar">My Wedding</h2>
                                <div class="area">
                                    <img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar2.png" alt="image description" width="47" height="47" />
                                    <div class="info">
                                        <ul class="list">
                                            <li><a class="photos" href="#">82 photos</a></li>
                                            <li><a class="time" href="#">Dec. 31, 2011</a></li>
                                            <li><a class="locked" href="#">Locked</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="block">
                                <a href="#" class="btn-download">Download album</a>
                            </div>
                            <div class="block">
                                <h2 class="stream">Stream</h2>
                                <ul class="list inner">
                                    <li>
                                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar3.png" width="43" height="43" alt="image description" />
                                        <div class="info">
                                            <p><a href="#">Joe uploaded a new photo</a></p>
                                            <p><em class="date">Dec. 31, 2011  |  Joe Average </em></p>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar4.png" width="43" height="43" alt="image description" />
                                        <div class="info">
                                            <p><a href="#">Homer is no following the album</a></p>
                                            <p><em class="date">Dec. 31, 2011  |  Joe Average </em></p>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar5.png" width="43" height="43" alt="image description" />
                                        <div class="info">
                                            <p><a href="#">Moe is no following the album</a></p>
                                            <p><em class="date">Dec. 31, 2011  |  Joe Average </em></p>
                                        </div>
                                    </li>
                                    <li>
                                        <img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar3.png" width="43" height="43" alt="image description" />
                                        <div class="info">
                                            <p><a href="#">Joe added a new photo to album</a></p>
                                            <p><em class="date">Dec. 31, 2011  |  Joe Average </em></p>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="block">
                                <h2 class="photographers">Photographers</h2>
                                <ul class="photographers-list">
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar6.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar7.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar8.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar9.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar10.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar11.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar12.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar10.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar13.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar14.png" width="43" height="44" alt="image description" /></a></li>
                                    <li><a href="#"><img src="<?php echo App::getBaseUrl() ?>/skin/images/img-avatar15.png" width="43" height="44" alt="image description" /></a></li>
                                </ul>
                                <a href="#" class="all">Show all</a>
                            </div>
                        </div>
                    </div>
                    <a href="#" class="opener">OPENER</a>
                </div>
                <div id="content">
                    <ul class="gallery">
                        <?php foreach ($bilder as $bild): ?>
                        <li class="png-box">
                            <div class="holder">
                                <div class="lt"></div>
                                <div class="t"></div>
                                <div class="rt"></div>
                                <div class="c">
                                    <div class="l"></div>
                                    <div class="content">
                                        <img src="/Tutkit_OOP_mit_PHP/Gallery/bilder/<?php echo $bild->getPath(); ?>" />
                                    </div>
                                    <div class="r"></div>
                                </div>
                                <div class="lb"></div>
                                <div class="b"></div>
                                <div class="rb"></div>
                            </div>
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="holder">
            <ul class="menu">
                <li><a href="#">Help</a></li>
                <li><a href="#">How it works</a></li>
                <li><a href="#">Terms of service</a></li>
                <li><a href="#">Blog</a></li>
                <li>
                    <?php if (\Session\User::isLoggedIn()): ?>
                        <a href="<?php echo App::getBaseUrl() ?>index/logout">Logout</a>
                    <?php else: ?>
                        <a href="<?php echo App::getBaseUrl() ?>index/login">Login</a>
                    <?php endif; ?>
                </li>
            </ul>
            <strong class="logo"><a href="#">Tribelens</a></strong>
            <ul class="social">
                <li><a class="twitter" href="#">twitter</a></li>
                <li><a class="facebook" href="#">facebook</a></li>
                <li><a class="google" href="#">google</a></li>
                <li><a href="#" class="dribbble">dribbble</a></li>
                <li><a href="#" class="flickr">flickr</a></li>
            </ul>
        </div>
    </div>
</div>
</body>
</html>